# Generated by Django 5.1.6 on 2026-06-13 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('provider', models.CharField(max_length=20)),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('geometry', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=500)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('origin_label', models.CharField(max_length=500)),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('dest_label', models.CharField(max_length=500)),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='trafficsample',
            new_name='commute_tra_vector_363d8f_idx',
            old_name='commute_tra_vector_2a1f7c_idx',
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to=settings.AUTH_USER_MODEL),
        ),
        # GiST earthdistance indexes for the spatial route-geometry cache
        # lookup (mirrors the TrafficSample indexes in 0001).
        migrations.RunSQL(
            sql=[
                "CREATE INDEX IF NOT EXISTS idx_route_origin_earth ON commute_routegeometry USING gist (ll_to_earth(origin_lat, origin_lng));",
                "CREATE INDEX IF NOT EXISTS idx_route_dest_earth ON commute_routegeometry USING gist (ll_to_earth(dest_lat, dest_lng));",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS idx_route_origin_earth;",
                "DROP INDEX IF EXISTS idx_route_dest_earth;",
            ],
        ),
    ]
