# Generated by Django 5.1.6 on 2026-06-15 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0003_cache_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'FREE'), ('PRO', 'PRO')], default='FREE', max_length=8)),
                ('sub_tier', models.CharField(blank=True, choices=[('', '—'), ('TRIAL', 'TRIAL'), ('COMP', 'COMP'), ('USER', 'USER'), ('TEAM', 'TEAM')], default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
